Repository BuxOrg/bux, pull requests merged in 2022-05, with the labels that each got.

#91 Admin Actions
  action_access_key.go
  action_blockheader.go
  action_destination.go
  action_destination_test.go
  action_draft_transaction.go
  action_paymails.go
  action_transaction.go
  action_utxo.go
  action_xpub.go
  admin_actions_stats.go
  admin_interface.go
  datastore/interface.go
  datastore/models.go
  datastore/mongodb.go
  datastore/mongodb_test.go
  datastore/params.go
  datastore/where.go
  datastore/where_test.go
  interface.go
  model_access_keys.go
  model_access_keys_test.go
  model_block_headers.go
  model_destinations.go
  model_draft_transactions.go
  model_get.go
  model_paymails.go
  model_transactions.go
  model_utxos.go
  model_xpubs.go
  utils/models.go
  utils/models_test.go
Labels: feature, update

#95 Model aggregate
  action_transaction.go
  admin_actions_stats.go
  admin_interface.go
  datastore/interface.go
  datastore/models.go
  datastore/mongodb.go
  model_get.go
  model_transactions.go
  model_utxos.go
Labels: feature, update

#96 Converted SendToAll to transaction output
  examples/client/custom_rates/custom_rates.go
  model_draft_transactions.go
  model_draft_transactions_test.go
  model_transaction_config.go
Labels: feature, update

#98 Set satoshis of SendToAll output to 0 before calculation of total
  model_draft_transactions.go
  model_draft_transactions_test.go
Labels: hot-fix

#99 Fixed incorrect satoshi value in empty (SendToAll) paymail outputs
  errors.go
  model_draft_transactions.go
  model_draft_transactions_test.go
  model_transaction_config.go
Labels: hot-fix

#102 Make sure transactions are synced in the correct order
  model_sync_transactions.go
Labels: hot-fix

#103 Changed http headers to be valid according to specs
  authentication_internal.go
Labels: hot-fix

#104 Added some tests and benchmarks, changed setAddress on draft transaction to only derive what is needed
  action_transaction_test.go
  bux_test.go
  model_destinations.go
  model_destinations_test.go
  model_xpubs_test.go
  utils/keys.go
  utils/keys_test.go
Labels: test, update

#105 Fix: increment model value not being updated on the model (hack)
  .make/go.mk
  model_xpubs.go
  models_internal.go
  paymail_service_provider.go
Labels: hot-fix, bug-P3

#81 Rename monitor methods and add channel cleanup
  chainstate/interface.go
  chainstate/monitor.go
  client_internal.go
  examples/client/monitor/monitor.go
  monitor_event_handler.go
Labels: stale, feature, update
