Repository BuxOrg/bux, pull requests merged in 2022-02, with the labels that each got.

#6 Fix for int overflow issue
  utils/utils.go
Labels: hot-fix, bug-P3

#5 Add an xpub importer library
  action_transaction.go
  chainstate/mock_whatsonchain_test.go
  client.go
  client_options.go
  go.mod
  go.sum
  importer/xpub.go
  interface.go
Labels: feature, update

#7 Update to use address history rather than bulk unspent
  action_xpub.go
  import.go
  interface.go
Labels: update

#8 Include used addresses for importer
  action_xpub.go
  import.go
Labels: update

#9 WIP: Move importer to bitbus
  action_xpub.go
  go.mod
  go.sum
  import.go
Labels: update

#10 Added OutputValue, Status and Direction to the output of actions
  model_transactions.go
Labels: update

#12 Updated authentication to allow non signed actions
  authentication.go
  authentication_internal.go
  authentication_test.go
Labels: update

#13 Added RemovePrivateData function to xpubs
  model_xpubs.go
Labels: update

#14 Added test for RemovePrivateData
  model_xpubs_test.go
Labels: test, update

#17 Changed signature of action methods to use WithMetadatas in options
  action_access_key.go
  action_destination.go
  action_destination_test.go
  action_transaction.go
  action_xpub.go
  import.go
  interface.go
  model_destinations_test.go
  model_transactions_test.go
  model_xpubs.go
  model_xpubs_test.go
Labels: feature, update
