Repository BuxOrg/bux, pull requests merged in 2022-06, with the labels that each got.

#111 Properly load monitored destinations and bloom filter fix
  chainstate/monitor.go
Labels: hot-fix

#112 Feature: Multi-server improvements for destination Monitoring
  action_transaction.go
  chainstate/monitor_client.go
  client_internal.go
  client_options.go
  definitions.go
  interface.go
  model_destinations.go
  monitor.go
  monitor_event_handler.go
  tasks.go
Labels: feature, update

#125 Added RecordRawTransaction action
  action_transaction.go
  interface.go
  utils/destination_types.go
  utils/destination_types_test.go
Labels: feature

#128 Fixed satoshi value of paymail outputs when more than 1 present
  model_transaction_config.go
  utils/outputs.go
  utils/outputs_test.go
Labels: hot-fix

#131 Added broadcasting of incoming transaction when attempting to broadcast
  action_transaction.go
  bux_suite_test.go
  model_incoming_transactions.go
  model_sync_transactions.go
  monitor.go
Labels: hot-fix

#132 Fixed incoming transactions processing
  chainstate/chainstate_test.go
  chainstate/processor_test.go
  chainstate/requirements.go
  chainstate/requirements_test.go
  model_incoming_transactions.go
  model_incoming_transactions_test.go
  model_sync_transactions.go
  tasks.go
Labels: hot-fix, update
