Repository BuxOrg/bux, pull requests merged in 2022-04, with the labels that each got.

#51 Add configurable options for monitoring
  chainstate/client_options.go
  chainstate/interface.go
  chainstate/monitor.go
  chainstate/processor.go
  chainstate/processor_test.go
  client.go
  client_internal.go
  monitor_event_handler.go
  utils/destination_types.go
Labels: work-in-progress, feature, update

#54 Bux Notifications (MVP)
  client.go
  client_internal.go
  client_options.go
  interface.go
  model_destinations.go
  model_transactions.go
  models_internal.go
  notifications/client.go
  notifications/client_options.go
  notifications/interface.go
  notifications/notifications.go
Labels: work-in-progress, feature

#58 Added GetPaymailAddress action
  action_paymails.go
  errors.go
  interface.go
Labels: feature, update

#60 Fixed transaction signing
  model_draft_transactions.go
  model_draft_transactions_test.go
  utils/scripts.go
Labels: hot-fix

#61 Added paymail get actions
  action_paymails.go
  interface.go
  model_paymails.go
Labels: feature, update

#63 Added logger to notifications options
  client_internal.go
  notifications/client.go
  notifications/client_options.go
  notifications/interface.go
  notifications/notifications.go
Labels: feature

#64 Added pagination to ReserveUtxos for large number of utxos in db
  model_draft_transactions.go
  model_options.go
  model_utxos.go
  model_utxos_test.go
  models.go
Labels: update

#66 Add block header socket processing
  action_blockheader.go
  chainstate/monitor_handler.go
  client_internal.go
  errors.go
  interface.go
  monitor_event_handler.go
  transaction_monitor_event_handler.go
Labels: update

#68 Initial token support via custom scripts in transaction config
  errors.go
  model_draft_transactions.go
  model_draft_transactions_test.go
  model_transaction_config.go
  model_transaction_config_test.go
  model_transactions.go
  model_transactions_test.go
  utils/destination_types.go
  utils/errors.go
  utils/tokens.go
  utils/tokens_test.go
Labels: feature, update

#72 Added datastore QueryParams
  action_access_key.go
  action_destination.go
  action_destination_test.go
  action_paymails.go
  action_transaction.go
  action_utxo.go
  datastore/interface.go
  datastore/models.go
  datastore/mongodb.go
  datastore/mongodb_test.go
  datastore/params.go
  datastore/params_test.go
  interface.go
  model_access_keys.go
  model_access_keys_test.go
  model_destinations.go
  model_draft_transactions.go
  model_get.go
  model_incoming_transactions.go
  model_paymails.go
  model_sync_transactions.go
  model_transactions.go
  model_transactions_test.go
  model_utxos.go
  model_utxos_test.go
  models_test.go
  monitor.go
  tasks.go
Labels: refactor, update

#69 Monitor 2.0
  action_blockheader.go
  chainstate/client_options.go
  chainstate/interface.go
  chainstate/monitor.go
  chainstate/monitor_client.go
  chainstate/processor.go
  chainstate/processor_test.go
  datastore/models.go
  definitions.go
  interface.go
  model_blockheaders.go
  monitor_event_handler.go
Labels: refactor, update

#77 Fixed possible race condition in waitgroup in monitor
  monitor_event_handler.go
Labels: hot-fix

#76 Fixed change output value based on correct fee calculation
  model_draft_transactions.go
  model_draft_transactions_test.go
  tests/model_draft_transaction_low_fee.json
Labels: hot-fix, update

#85 Fixed fee calculation more inline with actual bitcoin transactions
  definitions.go
  model_draft_transactions.go
  model_draft_transactions_test.go
  tests/model_draft_transactions_test.json
  utils/fees.go
  utils/fees_test.go
Labels: hot-fix, update

#90 Added UseForChange option for Outputs in TransactionConfig
  model_draft_transactions.go
  model_draft_transactions_test.go
  model_transaction_config.go
Labels: feature, update
