Repository BuxOrg/bux, pull requests merged in 2022-03, with the labels that each got.

#28 Updates from js client development
  action_access_key.go
  action_destination.go
  action_transaction.go
  action_utxo.go
  authentication.go
  authentication_test.go
  errors.go
  interface.go
  model_access_keys.go
  model_destinations.go
  model_destinations_test.go
  utils/keys.go
  utils/utils.go
  utils/utils_test.go
Labels: update

#24 Add paymail model from bux-server
  definitions.go
  errors.go
  model_metadata.go
  model_paymails.go
  model_paymails_test.go
  models_test.go
Labels: work-in-progress, update

#30 Changed read actions to use xpub ID instead of xpub keys
  action_access_key.go
  action_destination.go
  action_transaction.go
  action_xpub.go
  authentication.go
  go.mod
  go.sum
  interface.go
  model_transactions.go
  model_transactions_test.go
  model_xpubs_test.go
Labels: refactor, update

#31 Fixed tests for client updates
  action_destination_test.go
  action_xpub.go
  model_xpubs_test.go
Labels: hot-fix, bug-P3

#29 Add paymail actions and tests
  action_paymails.go
  action_paymails_test.go
  bux_suite_test.go
  interface.go
Labels: work-in-progress, refactor

#32 Fixed dust limit
  definitions.go
Labels: update

#33 Add support for internal paymail keys for identity usage
  errors.go
  model_paymails.go
  model_paymails_test.go
Labels: feature, update

#43 Changed the monitor field on destinations to be a null.Time instead of a boolean
  action_destination.go
  model_destinations.go
  model_destinations_test.go
  model_transaction_config_test.go
  model_transactions.go
Labels: update

#44 Fixed missing request missing in authentication return on error
  authentication.go
Labels: hot-fix

#46 Added update metadata function to destinations, transactions and xpub
  action_destination.go
  action_destination_test.go
  action_transaction.go
  action_xpub.go
  action_xpub_test.go
  interface.go
  model_transactions.go
  model_transactions_test.go
  models.go
  models_internal.go
Labels: feature, update
