Repository BuxOrg/bux, pull requests merged in 2023-10, with the labels that each got.

#417 feat(BUX-212/213): introduces codestandards/codeowners
  .github/CODEOWNERS
  .github/CODE_OF_CONDUCT.md
  .github/CODE_STANDARDS.md
  .github/CONTRIBUTING.md
  .github/FUNDING.yml
  .github/ISSUE_TEMPLATE/bug_report.yaml
  .github/ISSUE_TEMPLATE/config.yaml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.yaml
  .github/ISSUE_TEMPLATE/issue-template.md
  .github/ISSUE_TEMPLATE/question.yaml
  .github/PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE/general.md
  .github/SECURITY.md
  .github/SUPPORT.md
Labels: feature

#420 fix(BUX-252): beef econding issues
  beef_tx.go
  beef_tx_bytes.go
  beef_tx_sorting.go
  beef_tx_sorting_test.go
  beef_tx_test.go
  model_sync_transactions.go
  paymail.go
Labels: bug-P3

#416 feat(BUX-164): verify merkle roots
  chainstate/client.go
  chainstate/client_options.go
  chainstate/definitions.go
  chainstate/interface.go
  chainstate/merkle_root.go
  chainstate/merkle_root_provider.go
  chainstate/mock_const.go
  chainstate/transaction.go
  client_options.go
  go.mod
  go.sum
  mock_chainstate_test.go
  paymail_mocks_test.go
  paymail_service_provider.go
Labels: feature

#428 chore: update go-paymail and go-broadcast-client version
  definitions.go
  go.mod
  go.sum
Labels: update

#440 fix(BUX-287): failed tests on local machine
  chainstate/broadcast_test.go
  chainstate/client_test.go
  chainstate/transaction_test.go
Labels: feature

#437 chore(BUX-297): add more logs
  chainstate/client.go
  paymail.go
Labels: update

#442 feat(BUX-293): calculate and store BUMP in DB
  definitions.go
  model_bump.go
  model_merkle_proof.go
  model_merkle_proof_test.go
  model_sync_transactions.go
  model_transactions.go
Labels: feature

#438 chore(BUX-298): refactor sync method and use go-b t structures in BEEF implementation
  beef_tx.go
  beef_tx_bytes.go
  beef_tx_sorting.go
  beef_tx_sorting_test.go
  model_sync_transactions.go
Labels: update

#436 feat(BUX-291): initial refactorization
  model_sync_transactions.go
  model_sync_transactions_test.go
  sync_tx_repository.go
  sync_tx_service.go
Labels: feature

#443 feat(BUX-291): split model_transactions into smaller files
  db_model_transactions.go
  model_transactions.go
  model_transactions_test.go
  tx_repository.go
  tx_service.go
Labels: feature

#447 feat: revert BUMP calculation to sync task
  sync_tx_service.go
Labels: feature

#449 feat(BUX-295): encoding BUMP in BEEF
  beef_tx.go
  beef_tx_bytes.go
  beef_tx_test.go
  model_bump.go
  model_draft_transactions.go
Labels: feature
