Repository BuxOrg/bux, pull requests merged in 2023-12, with the labels that each got.

#488 feat(BUX-358): remove check tx job
  action_transaction.go
  client_options.go
  definitions.go
  errors.go
  interface.go
  model_draft_transactions_test.go
  model_incoming_transactions.go
  model_transaction_config.go
  model_transactions.go
  model_transactions_test.go
  monitor_event_handler.go
  record_tx_strategy_external_incoming_tx.go
  record_tx_strategy_outgoing_tx.go
  sync_tx_service.go
  tasks.go
  tx_service.go
Labels: feature

#497 feat(BUX-168, BUX-172): BEEF v2 (unmined inputs) + complex SPV
  action_transaction.go
  action_transaction_test.go
  beef_bump.go
  beef_fixtures.go
  beef_tx.go
  beef_tx_mock.go
  beef_tx_test.go
  chainstate/definitions.go
  chainstate/merkle_root_provider.go
  chainstate/transaction.go
  chainstate/transaction_info.go
  client_options.go
  db_model_transactions.go
  definitions.go
  errors.go
  go.mod
  go.sum
  interface.go
  model_bump.go
  model_bump_test.go
  model_draft_transactions.go
  model_draft_transactions_test.go
  model_incoming_transactions.go
  model_incoming_transactions_test.go
  model_merkle_proof.go
  model_merkle_proof_test.go
  model_sync_transactions_test.go
  model_transaction_config.go
  model_transactions.go
  model_transactions_test.go
  monitor_event_handler.go
  paymail.go
  paymail_mocks_test.go
  paymail_service_provider.go
  record_tx_strategy_external_incoming_tx.go
  record_tx_strategy_outgoing_tx.go
  sync_tx_service.go
  tasks.go
  tx_repository.go
  tx_service.go
Labels: feature

#498 chore(BUX-XXX): update to go-paymail v 0.9.4
  go.mod
  go.sum
Labels: chore, update

#504 Chore(BUX-000) clean tests logs
  bux_test.go
  chainstate/chainstate_test.go
  chainstate/client_options_test.go
  client_options_test.go
  client_test.go
  definitions.go
  logging/logging.go
  model_transaction_config_test.go
  paymail_test.go
  taskmanager/client_options_test.go
Labels: update

#509 feat(BUX-207): add logger to go-paymail config
  client_internal.go
  go.mod
  go.sum
Labels: feature

#513 chore(BUX-416) disable monitor
  client_options.go
  cron_job_declarations.go
  definitions.go
  examples/client/monitor/monitor.go
Labels: update

#517 perf(BUX-000): refactorize P2P - send tx to the receiver only once
  record_tx_strategy_outgoing_tx.go
  sync_tx_service.go
  utils.go
Labels: feature
