Repository BuxOrg/bux, pull requests merged in 2023-07, with the labels that each got.

#328 fix: fixes empty sender's paymail
  action_paymails.go
  model_draft_transactions.go
  model_transaction_config.go
  model_transaction_config_test.go
Labels: bug-P3

#332 fix(BUX-117): fix writelock for bux to bux txs
  action_transaction.go
Labels: bug-P3

#331 feat(BUX-99): validation and customization of mAPI config
  bux_suite_test.go
  bux_test.go
  chainstate/chainstate_test.go
  chainstate/client.go
  chainstate/client_internal.go
  chainstate/client_options.go
  chainstate/client_options_test.go
  chainstate/client_test.go
  chainstate/interface.go
  chainstate/mock_const.go
  chainstate/mock_minercraft.go
  client_options.go
  client_options_test.go
  mock_chainstate_test.go
  paymail_test.go
Labels: refactor, feature

#333 Perf speed up tx broadcasting
  chainstate/broadcast.go
  chainstate/broadcast_providers.go
  chainstate/broadcast_test.go
  chainstate/broadcast_utils.go
  chainstate/chainstate.go
  chainstate/mock_minercraft.go
  chainstate/mock_nownodes_test.go
  chainstate/mock_whatsonchain_test.go
Labels: refactor, feature

#334 feat(BUX-27): makes XPubID field public
  action_transaction.go
  action_transaction_test.go
  model_sync_transactions.go
  model_transactions.go
  model_transactions_test.go
Labels: feature

#336 fix(BUX-136): internal paymail transaction bug
  paymail_service_provider.go
Labels: bug-P3

#338 fix(BUX-114): stop creating new destination when paymail alias is checked only for existence.
  paymail_service_provider.go
Labels: bug-P3

#339 feat(BUX-51): go-minercraft v2
  chainstate/broadcast.go
  chainstate/broadcast_providers.go
  chainstate/broadcast_test.go
  chainstate/client.go
  chainstate/client_internal.go
  chainstate/client_options.go
  chainstate/client_options_test.go
  chainstate/client_test.go
  chainstate/interface.go
  chainstate/mock_minercraft.go
  chainstate/transaction.go
  client_options.go
  examples/client/broadcast_miners/broadcast_miners.go
  examples/client/custom_rates/custom_rates.go
  go.mod
  go.sum
  mock_chainstate_test.go
Labels: feature

#345 Feat: add new transaction task
  client_options.go
  definitions.go
  model_transaction_config.go
  model_transactions.go
  tasks.go
Labels: feature
