Repository BuxOrg/bux, pull requests merged in 2024-02, with the labels that each got.

#567 fix: try broadcast outgoing tx again
  cron_job_declarations.go
  sync_tx_service.go
Labels: bug-P3

#556 BUX-491: Admin delete paymail
  action_paymails.go
  action_paymails_test.go
  errors.go
  paymail_service_provider.go
Labels: feature

#572 chore(BUX-000): unused DownloadAndUnzipFile function
  utils/download.go
Labels: tested

#548 BUX-480: Record Transaction
  action_transaction_test.go
  paymail_service_provider.go
  record_tx.go
  record_tx_strategy_external_incoming_tx.go
  record_tx_strategy_internal_incoming_tx.go
  record_tx_strategy_outgoing_tx.go
Labels: feature, tested

#592 feat(BUX-586): mark repository as deprecated
  README.md
Labels: tested
