Repository BuxOrg/bux, pull requests merged in 2024-01, with the labels that each got.

#520 Chore(bux-000) make datastore quiet
  client_options.go
  definitions.go
Labels: update

#521 feat(BUX-418, BUX-166): use Arc with gorillapool as a default option
  chainstate/broadcast.go
  chainstate/broadcast_test.go
  chainstate/client.go
  chainstate/client_options_test.go
  chainstate/client_test.go
  chainstate/definitions.go
  chainstate/mock_const.go
  chainstate/requirements.go
  chainstate/requirements_test.go
  chainstate/transaction.go
  chainstate/transaction_info.go
  chainstate/transaction_test.go
  definitions.go
  go.mod
  go.sum
  model_bump.go
  model_bump_test.go
  model_transactions.go
  utils/utils.go
Labels: feature

#530 feat(BUX-000): restore translation mechanism
  chainstate/broadcast_providers.go
  go.mod
  go.sum
Labels: feature

#533 fix(BUX-461) fee quotes for both arc and mAPI with user defined fee quote
  chainstate/broadcast_client_init.go
  chainstate/broadcast_providers.go
  chainstate/client.go
  chainstate/client_internal.go
  chainstate/client_options.go
  chainstate/client_options_test.go
  chainstate/client_test.go
  chainstate/definitions.go
  chainstate/interface.go
  chainstate/minercraft_default.go
  chainstate/minercraft_init.go
  chainstate/mock_const.go
  chainstate/mock_minercraft.go
  chainstate/transaction.go
  client_options.go
  definitions.go
  examples/client/broadcast_miners/broadcast_miners.go
  examples/client/custom_rates/custom_rates.go
  mock_chainstate_test.go
  model_draft_transactions.go
  model_draft_transactions_test.go
  model_transaction_config_test.go
  utils/fees.go
  utils/fees_test.go
Labels: bug-P3

#532 feat(BUX-417): remove monitor, ITC flag and IncomingTransaction
  action_destination.go
  action_destination_test.go
  action_transaction.go
  bux_suite_test.go
  chainstate/chainstate.go
  chainstate/client.go
  chainstate/client_options.go
  chainstate/definitions.go
  chainstate/errors.go
  chainstate/interface.go
  chainstate/monitor.go
  chainstate/monitor_client.go
  client.go
  client_internal.go
  client_options.go
  client_options_test.go
  cron_job_declarations.go
  cron_job_definitions.go
  definitions.go
  examples/client/custom_cron/custom_cron.go
  interface.go
  locks.go
  mock_chainstate_test.go
  model_destinations.go
  model_destinations_test.go
  model_incoming_transactions.go
  model_incoming_transactions_test.go
  model_transaction_config_test.go
  model_transactions.go
  model_transactions_test.go
  models_test.go
  monitor.go
  monitor_event_handler.go
  paymail_service_provider.go
  record_tx_strategy_external_incoming_tx.go
Labels: feature

#537 chore(BUX-417): remove address resolution methods
  client.go
  client_internal.go
  client_options.go
  client_paymail.go
  client_test.go
  definitions.go
  examples/client/mysql/mysql.go
  examples/client/paymail_support/paymail_support.go
  model_draft_transactions.go
  model_transaction_config.go
  model_transaction_config_test.go
  paymail.go
  paymail_test.go
Labels: feature

#538 fix(BUX-474): prevent panics in UnReserveUtxos and VerifyMerkleRoots
  action_utxo.go
  chainstate/merkle_root.go
Labels: bug-P3

#539 fix(BUX-312): hanging transactions on database
  model_save.go
Labels: bug-P3

#542 docs(BUX-442): updates readme and code standards
  .github/CODE_STANDARDS.md
  README.md
Labels: documentation

#540 BUX-477: GetAccessKey error message
  action_access_key.go
  errors.go
Labels: feature

#522 BUX-433/Change readme
  README.md
Labels: feature

#546 fix(BUX-497): update to go-paymail 12.1
  go.mod
  go.sum
  paymail_test.go
Labels: bug-P3

#549 chore(BUX-351): improve logging when requesting Pulse
  chainstate/client.go
  chainstate/client_options.go
  chainstate/merkle_root.go
  chainstate/merkle_root_provider.go
  chainstate/merkle_root_test.go
Labels: update

#553 feat(BUX-525): remove unused graphql methods
  action_destination.go
  go.mod
  model_ids.go
  model_ids_test.go
  model_metadata.go
  model_metadata_test.go
Labels: feature

#557 BUX-496: Admin record transactions
  errors.go
Labels: feature
